### ISSUE TITLE
Inconsistent limits on document sizes

### ISSUE THREAD

**Issue by porkbrain** [awsdocs/amazon-textract-developer-guide#12]
A [document](doc_source/limits.md) in this repo limits upload to **10MB**:
> The maximum document image (JPEG/PNG) size is 10 MB. 

[AWS SDK](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Textract.html#detectDocumentText-property) and Textract console demo limits upload to **5MB**:
> The maximum size of a document that's provided in a blob of bytes is 5 MB. The document bytes must be in PNG or JPEG format.
\
The maximum size of a document that's stored in an S3 bucket is 5 MB.

**Comment by vivibigham** [comment]
Hello! The console currently has different limits than the API, which is what's listed in the document

**Comment by porkbrain** [comment]
Thank you for your answer, that makes sense.
