### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by dwitiyabhatt** [awsdocs/amazon-textract-developer-guide#14]
In android, I am using following dependencies :

  implementation 'com.amazonaws:aws-java-sdk-textract:1.11.926'
  implementation 'com.amazonaws:aws-java-sdk-sqs:1.11.926'
  implementation 'com.amazonaws:aws-java-sdk-sns:1.11.926'

On this line It is being crashed :

sns = AmazonSNSClientBuilder.defaultClient();

Error is : 
java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar!classes3.dex

**Comment by vivibigham** [comment]
Hello! I'll hunt around for the solution to this problem with the service team. Sorry for the late response!

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
