### ISSUE TITLE
Didn't get BlockType:table when use get_document_text_detection

### ISSUE THREAD

**Issue by patelmm** [awsdocs/amazon-textract-developer-guide#4]
Hi,
Follow [this](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/textract.html#Textract.Client.start_document_text_detection) document. 
Actually image have table layout with text but i didn't get **BlockType table** in response when use **get_document_text_detection** function. If i'm sue **analyze_document** then get table data. Actually upload file need support png and pdf so we need to use **get_document_text_detection**

Can you please help me out?

**Comment by schadem** [comment]
Only analyze_document with features TABLES will return table information, document_text_detection does not perform table analysis.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
