### ISSUE TITLE
Result from textract api is different from console

### ISSUE THREAD

**Issue by herruli** [awsdocs/amazon-textract-developer-guide#6]
I have copied the python code on textract example page: https://docs.aws.amazon.com/textract/latest/dg/examples-export-table-csv.html and the result is poor. However, the performance in console page is far better than python, as the numbers are aligned correctly.

Can anyone share about how to tweak the API to make it more like the one in the console? Thanks

**Comment by vivibigham** [comment]
Hi! I'm the current doc writer for Textract. Sorry for such a late response, I'll check in with the service team regarding this and keep you updated with their reply.

**Comment by simosca92** [comment]
Hi @vivibigham, I'm dealing with the same issue. Are there any updates?

Thanks,
Simone

**Comment by jordan-barrett-jm** [comment]
Hi I have the same issue. Is there a fix?

**Comment by jordan-barrett-jm** [comment]
Found a fix - use this library instead https://github.com/aws-samples/amazon-textract-textractor

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
